# Avizo Project
# Avizo
# Generated by Avizo 8.1.1
remove -all
remove "physics.icol" "REMUS_PATH" "Colormap Legend" "myPickingSlice"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 0
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 253 40
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 26 350
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 65535

set hideNewModules 0
[ load /var/remote/projects/kaust/earthenvironscience/water_desal_reuse/AUV_ADCP/Viz_Lab/REMUS_PATH.am ] setLabel "REMUS_PATH"
"REMUS_PATH" setIconPosition 15 9
"REMUS_PATH" master disconnect
"REMUS_PATH" fire
"REMUS_PATH" setViewerMask 65535

set hideNewModules 0
create HxDisplayColormap "Colormap Legend"
"Colormap Legend" setIconPosition 428 41
"Colormap Legend" setVar "CustomHelp" {HxDisplayColormap}
"Colormap Legend" data connect "physics.icol"
"Colormap Legend" fire
"Colormap Legend" options setState item 0 0 item 1 0 item 2 0 item 3 1 item 4 1 color 5 0 0 0 item 7 1 
"Colormap Legend" fontSettings setState name: "Sans Serif" size: 18 buttonText: Select bold: 1 italic: 0 color: 1 1 1
"Colormap Legend" position setMinMax 0 -2000 2000
"Colormap Legend" position setValue 0 100
"Colormap Legend" position setMinMax 1 -2000 2000
"Colormap Legend" position setValue 1 100
"Colormap Legend" size setMinMax 0 0 1000
"Colormap Legend" size setValue 0 300
"Colormap Legend" size setMinMax 1 0 1000
"Colormap Legend" size setValue 1 25
"Colormap Legend" labels setState {0.113209/Low 0.526953/Medium 0.940696/High}
"Colormap Legend" title setState {Turbidity Raw (NTU)}
"Colormap Legend" fire
"Colormap Legend" setViewerMask 65535
"Colormap Legend" setShadowStyle 0
"Colormap Legend" setPickable 1

set hideNewModules 0
create myPickingSlice "myPickingSlice"
"myPickingSlice" setIconPosition 220 8
"myPickingSlice" setVar "CustomHelp" {myPickingSlice}
"myPickingSlice" data connect "REMUS_PATH"
"myPickingSlice" colormap setDefaultColor 1 0 0
"myPickingSlice" colormap setDefaultAlpha 0.800000
"myPickingSlice" colormap setLocalRange 1
"myPickingSlice" colormap setLocalMinMax 25.000000 350.000000
"myPickingSlice" colormap enableAlpha 1
"myPickingSlice" colormap enableAlphaToggle 0
"myPickingSlice" colormap setAutoAdjustRangeMode 1
"myPickingSlice" colormap setColorbarMinMax -15.4639 350
"myPickingSlice" colormap connect "physics.icol"
"myPickingSlice" projection disconnect
"myPickingSlice" fire
"myPickingSlice" color setIndex 0 7
"myPickingSlice" options setValue 0 1
"myPickingSlice" options setToggleVisible 0 1
"myPickingSlice" options setValue 1 0
"myPickingSlice" options setToggleVisible 1 1
"myPickingSlice" options setValue 2 1
"myPickingSlice" options setToggleVisible 2 1
"myPickingSlice" options setValue 3 0
"myPickingSlice" options setToggleVisible 3 1
"myPickingSlice" options setValue 4 0
"myPickingSlice" options setToggleVisible 4 1
"myPickingSlice" filter setState (d>-7.72354)
"myPickingSlice" pointSize setMinMax 0 10
"myPickingSlice" pointSize setButtons 1
"myPickingSlice" pointSize setEditButton 1
"myPickingSlice" pointSize setIncrement 1
"myPickingSlice" pointSize setValue 1
"myPickingSlice" pointSize setSubMinMax 0 10
"myPickingSlice" scaleData setIndex 0 0
"myPickingSlice" sphereScale setMinMax -1 1
"myPickingSlice" sphereScale setButtons 0
"myPickingSlice" sphereScale setEditButton 1
"myPickingSlice" sphereScale setIncrement 0.133333
"myPickingSlice" sphereScale setValue -0.443787
"myPickingSlice" sphereScale setSubMinMax -1 1
"myPickingSlice" setBondWidth 1
"myPickingSlice" setBondColor 0 0 0.1
"myPickingSlice" fire
"myPickingSlice" pointSize setMinMax 0 10
"myPickingSlice" pointSize setButtons 1
"myPickingSlice" pointSize setEditButton 1
"myPickingSlice" pointSize setIncrement 1
"myPickingSlice" pointSize setValue 1
"myPickingSlice" pointSize setSubMinMax 0 10
"myPickingSlice" fire
"myPickingSlice" setViewerMask 65535
"myPickingSlice" select
"myPickingSlice" setShadowStyle 0
"myPickingSlice" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.121353 -0.0821714 0.989202 5.0767
viewer 0 setCameraPosition -957.001 585.826 478.113
viewer 0 setCameraFocalDistance 62.9477
viewer 0 setCameraNearDistance 426.124
viewer 0 setCameraFarDistance 548.008
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

theObjectPool setSelectionOrder myPickingSlice
